# Generated by Django 3.0.2 on 2020-02-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
