# Generated by Django 3.0.2 on 2020-02-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_wine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='description',
        ),
    ]
