# Generated by Django 3.0.2 on 2020-02-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_wine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(default='image/wine_image.jpg', max_length=144, upload_to='wine_images/'),
        ),
    ]
