# Generated by Django 3.0.2 on 2020-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='rate_stacked',
            field=models.IntegerField(default=0),
        ),
    ]
